### ISSUE TITLE
Blogs meta component : Contents listing

### ISSUE THREAD

**Issue by akramsarkis** [Geeks-Solutions/vue-components#31]
Design link: https://www.figma.com/file/Le6xk0DI4om1Kq1SrzKinb/BO-geeks-app?type=design&node-id=1448-897&mode=design&t=ALIr1IEdEoHuk88e-0

Here the json collection: 

[BLOGS.postman_collection.json](https://github.com/Geeks-Solutions/vue-components/files/14775619/BLOGS.postman_collection.json)

**Important**: Hussein ignore the fact that when clicking on the article on the listing, the view mode show on the right, have each article taking the width of the screen 

**Important 2**: Of course the different element like search, filter should reflect what we have already in the BOs to have the same look and feel everywhere

- [ ] Similarly with what we have for media, we need a meta component to manage the articles

**Articles listing**

- [ ] The listing will show each article wit the below information
- Picture thumbnail
- Title of the article
- Short description of the article
- Last update date
- If the article is published or not : this should be an eye icon, open if published, closed if unpublished
- Add the Author name before the eye icon
- Have the edit and delete button inside each card  on the top right

````
GET /api/v1/project/5/articles/author HTTP/1.1
Host: blogs.k8s-dev.geeks.solutions
token: SFMyNTY.g2gDdAAAAARtAAAADGxvZ2luX2ZpZWxkc3QAAAABbQAAAAVlbWFpbG0AAAAfYS5zYXJraXMrdGVzdDVibG9nZGV2QGV3ZWV2LmNvbW0AAAARcHJvamVjdF9sb2dnZWRfaW5tAAAAGDY1YWUyYTg5MTM1MzE2MDAwNzlmNzI4Nm0AAAAKdG9rZW5fdHlwZW0AAAAGbm9ybWFsbQAAAAd1c2VyX2lkbQAAABg2NWIyMWY3ZjEzNTMxNjAwMDdiNmNjYzBuBgBHndbqjQFiAAFRgA.I1JQIZStkFfWC8O3Gu3ww4YsZeAuJOo2tm0wTrEDMDY
origin: https://blogmaiori.com

````

- [ ] We must be able to search an article by ( You need to use the filters component we already have)
- Title ( Key is title)
- Author name ( Key for now is author_id)

````
POST /api/v1/project/5/published_articles HTTP/1.1
Host: blogs.k8s-dev.geeks.solutions
origin: https://blogmaiori.com
Content-Type: application/json
Content-Length: 202

{
    "sort": {
        "created": "ASC"
    },
     "filters": [
        {
            "key": "author_id",
            "operation":"=",
            "value": "65b21f7f1353160007b6ccc0"
        }
    ]
}
````

- [ ] We must be able to filter by ( You need to use the filters component we already have)
- Status ( If published or not ) ( key is published  and value is boolean)
- Number of views ( key is views and it needs operator between the key and the value)
- Creation date : Should be a range
- Last update date: Should be a range
- Type ( Key is type)
- Categories ( Key is categories )

````
POST /api/v1/project/5/published_articles HTTP/1.1
Host: blogs.k8s-dev.geeks.solutions
origin: https://blogmaiori.com
Content-Type: application/json
Content-Length: 153

{
    "sort": {
        "created": "ASC"
    },
     "filters": [
        {
            "key": "categories",
            "value": ["2"]
        }
    ]
}
````

- [ ] We need an option to Create a new content

**Acceptance testing**

- [ ] Have the listing of the articles displayed correctly wit the correct data and as design
- [ ] Have the filters and search working fine
- [ ] Have the option to create a new content available and redirecting to the create content page

**Comment by akramsarkis** [comment]
@mahfouzhseineweev  it should be like the below for both created and updated but for now it is returning internal server error I don't know why,  I will add it in the bugs issue for blogs to julien and indicate him to adjust it to be able have a range like requested, for now skip this one if you want till julien fix it



````
"filters": [
        {
            "key": "created",
            "value": 1706606152
        }
            
    ]
````

**Comment by mahfouzhseineweev** [comment]
@akramsarkis Here are the props and their values that I have used to build this component

```
authToken: 'SFMyNTY.g2gDdAAAAARtAAAADGxvZ2luX2ZpZWxkc3QAAAABbQAAAAVlbWFpbG0AAAAfYS5zYXJraXMrdGVzdDVibG9nZGV2QGV3ZWV2LmNvbW0AAAARcHJvamVjdF9sb2dnZWRfaW5tAAAAGDY1YWUyYTg5MTM1MzE2MDAwNzlmNzI4Nm0AAAAKdG9rZW5fdHlwZW0AAAAGbm9ybWFsbQAAAAd1c2VyX2lkbQAAABg2NWIyMWY3ZjEzNTMxNjAwMDdiNmNjYzBuBgAc51i2kQFiAAFRgA.jg17okb3Cs5sA64jHW5YuFdqypTwqb147LGG9mYNV3k',
    blogsUriProp: "/api/v1/project/5/published_articles",
    authorsUriProp: '/api/v1/project/5/users',
    categoriesUriProp: '/api/v1/project/5/categories',
    showCreateBlogButton: true,
   ```

**Comment by akramsarkis** [comment]
Here some feedbacks regarding Chromatic:

**Points that needs backend ( I added them to not forgot them)**

- [ ] For the filters we need the one by Last update date and  created date ( As discussed let's wait the backend to be done for those to add them )
- [ ] Author name is missing but this is because it is missing from blogs backend, once fixed it needs to be added

**Points that can be checked now**

- [ ] There is no way to add or remove filters if needed ? I think we have this for the others BO
- [ ] I saw in the card component that you added a by the author, I know that now we have only the id but why the by is not showing in the listing

<img width="429" alt="Screenshot 2024-09-03 at 12 02 48" src="https://github.com/user-attachments/assets/c7ae203b-cd4d-4cbb-ac5f-67913f7a9e94">
