### ISSUE TITLE
Blogs meta component : Create new content

### ISSUE THREAD

**Issue by akramsarkis** [Geeks-Solutions/vue-components#32]
Design link: https://www.figma.com/file/Le6xk0DI4om1Kq1SrzKinb/BO-geeks-app?type=design&node-id=1448-897&mode=design&t=ALIr1IEdEoHuk88e-0

**Note**: The design is there to help you, you need to use the element we already have to adapt it with them

- [ ] We have a form to create an an article that includes:
- Name of the article : Required
- Path of the article : Required and unique : This one will be filled in automatically using the name entered but i must be able to edit it.
- Content type : For now we will have only Article and it is required
- Time to read : This will come from the metadata of the article where there is the unit and the duration
- Author name : The name of the user connected not editable
- Tags : list of tags available and an option to add new a tag that will open a tag field and when entering it and validating it, it will be added to the listing and selected
- Images : This will use media meta component to upload a media, as we can upload several media, so we need to have an upload image field by default and an option to add more image and if we add an image we must be able to remove it to have only one image for the media : Required
- Content description that is a Wyzywyg: Required
- Categories: listing of the categories available with an option to add a new one if needed, it will open a field to enter the new category with a button to add : Required

````
POST /api/v1/project/5/categories HTTP/1.1
Host: blogs.k8s-dev.geeks.solutions
token: SFMyNTY.g2gDdAAAAARtAAAADGxvZ2luX2ZpZWxkc3QAAAABbQAAAAVlbWFpbG0AAAAfYS5zYXJraXMrdGVzdDVibG9nZGV2QGV3ZWV2LmNvbW0AAAARcHJvamVjdF9sb2dnZWRfaW5tAAAAGDY1YWUyYTg5MTM1MzE2MDAwNzlmNzI4Nm0AAAAKdG9rZW5fdHlwZW0AAAAGbm9ybWFsbQAAAAd1c2VyX2lkbQAAABg2NWIyMWY3ZjEzNTMxNjAwMDdiNmNjYzBuBgBHndbqjQFiAAFRgA.I1JQIZStkFfWC8O3Gu3ww4YsZeAuJOo2tm0wTrEDMDY
origin: https://blogmaiori.com
Content-Type: application/json
Content-Length: 31

{
    "title": "Category new"
}
````
- Suggested articles: This is a listing where I can select the articles I would like to suggest when reading the article I am creating, of course this fields must be editable ( I must be able to add an additional article, I must be able to remove one suggested article)
-  Published as a drop down list that contains 3 values ( Draft, Published, Unpublished ) should not be editable if the user is not a publisher and should have value published by default
- There is an option to Cancel and an option to save, if I cancel I am back to the listing, If I Save the article is saved and you are redirected to the listing with the article added in the beginning

**Acceptance testing**

- [ ] The form to add a content must be displayed correctly showing which fields are required
- [ ] When saving without filling the required fields, error should show for the concerned field
- [ ] I must be able to add/edit and delete a category
- [ ] I must be able to add new tags
- [ ] I must be able to add suggested articles
- [ ] If I cancel I will be redirected to the listing but without any article added
- [ ] If I save I will be redirected to the listing with the new article added in the beginning

**Comment by akramsarkis** [comment]
@mahfouzhseineweev the link is the same one , here a screenshot of the design you need to use to help you even though you are using library component


![Uploading Screenshot 2024-09-03 at 11.39.43.png…]()
