### ISSUE TITLE
Blogs meta component: Edit/ Delete content

### ISSUE THREAD

**Issue by akramsarkis** [Geeks-Solutions/vue-components#33]
Design link: https://www.figma.com/file/Le6xk0DI4om1Kq1SrzKinb/BO-geeks-app?type=design&node-id=1448-897&mode=design&t=ALIr1IEdEoHuk88e-0

**Note** : The design is there to help you , but it needs adaptation

- Don't take into consideration the graph of views, we don't need it
- Don't take into consideration to publisher comments as it is not available now backend wize

**Edit content**

- [ ] The form is the same one as the create one except that the fields are prefilled with the values and I must be able to edit them except the author name
- If the article is unpublished, then the update is done on this article
- If the article is published then when I will edit and use the update article, it will create a draft article, so this must show somewhere in the listing and  when editing the draft that this is a draft of article id X name Y

Get article

````
GET /api/v1/project/5/articles/2 HTTP/1.1
Host: blogs.k8s-dev.geeks.solutions
origin: https://blogmaiori.com
token: SFMyNTY.g2gDdAAAAARtAAAADGxvZ2luX2ZpZWxkc3QAAAABbQAAAAVlbWFpbG0AAAAaYS5zYXJraXMrYXV0aG9yMkBld2Vldi5jb21tAAAAEXByb2plY3RfbG9nZ2VkX2lubQAAABg2NWFlMmE4OTEzNTMxNjAwMDc5ZjcyODZtAAAACnRva2VuX3R5cGVtAAAABm5vcm1hbG0AAAAHdXNlcl9pZG0AAAAYNjViMjMyNDYxMzUzMTYwMDA3ZTMyYTVkbgYA-vsjQI0BYgABUYA.h6MYMB8EmqQTNksnxFiOa6-cm32oWubef0ASrddDrMs
````

Edit article

````
PUT /api/v1/project/5/articles/17 HTTP/1.1
Host: blogs.k8s-dev.geeks.solutions
origin: https://blogmaiori.com
token: SFMyNTY.g2gDdAAAAARtAAAADGxvZ2luX2ZpZWxkc3QAAAABbQAAAAVlbWFpbG0AAAAfYS5zYXJraXMrdGVzdDVibG9nZGV2QGV3ZWV2LmNvbW0AAAARcHJvamVjdF9sb2dnZWRfaW5tAAAAGDY1YWUyYTg5MTM1MzE2MDAwNzlmNzI4Nm0AAAAKdG9rZW5fdHlwZW0AAAAGbm9ybWFsbQAAAAd1c2VyX2lkbQAAABg2NWIyMWY3ZjEzNTMxNjAwMDdiNmNjYzBuBgBHndbqjQFiAAFRgA.I1JQIZStkFfWC8O3Gu3ww4YsZeAuJOo2tm0wTrEDMDY
Content-Type: application/json
Content-Length: 38

{
   "categories": [
        2
    ]
}
````

- [ ] In the edit form there will be a toggl to publish or not the article, this one should be in a bloc alone as  there is endpoint to publish and unpublish
- So if I edit and the toggl is disabled and I enable it , this is the publish article that will be called
- If I edit and the toggl is enabled and I disable it, this is the unpublish article that will be called
- If I publish a draft, the original article will be updated and the draft will be removed, so I should have a success message and redirected to the listing with the draft removed from it
- This is available only for the admin or a publisher , so if the user logged in is neither admin nor publisher, this toggl will be disabled

Publish

````
PUT /api/v1/project/5/articles/170/publish HTTP/1.1
Host: blogs.k8s-dev.geeks.solutions
origin: https://blogmaiori.com
token: SFMyNTY.g2gDdAAAAARtAAAADGxvZ2luX2ZpZWxkc3QAAAABbQAAAAVlbWFpbG0AAAAfYS5zYXJraXMrdGVzdDVibG9nZGV2QGV3ZWV2LmNvbW0AAAARcHJvamVjdF9sb2dnZWRfaW5tAAAAGDY1YWUyYTg5MTM1MzE2MDAwNzlmNzI4Nm0AAAAKdG9rZW5fdHlwZW0AAAAGbm9ybWFsbQAAAAd1c2VyX2lkbQAAABg2NWIyMWY3ZjEzNTMxNjAwMDdiNmNjYzBuBgBHndbqjQFiAAFRgA.I1JQIZStkFfWC8O3Gu3ww4YsZeAuJOo2tm0wTrEDMDY

````

Unpublish

````
PUT /api/v1/project/5/articles/2/unpublish HTTP/1.1
Host: blogs.k8s-dev.geeks.solutions
origin: https://blogmaiori.com
token: SFMyNTY.g2gDdAAAAARtAAAADGxvZ2luX2ZpZWxkc3QAAAABbQAAAAVlbWFpbG0AAAAfYS5zYXJraXMrdGVzdDVibG9nZGV2QGV3ZWV2LmNvbW0AAAARcHJvamVjdF9sb2dnZWRfaW5tAAAAGDY1YWUyYTg5MTM1MzE2MDAwNzlmNzI4Nm0AAAAKdG9rZW5fdHlwZW0AAAAGbm9ybWFsbQAAAAd1c2VyX2lkbQAAABg2NWIyMWY3ZjEzNTMxNjAwMDdiNmNjYzBuBgBHndbqjQFiAAFRgA.I1JQIZStkFfWC8O3Gu3ww4YsZeAuJOo2tm0wTrEDMDY
````
- [ ] To remove a category for an article the below endpoint should be called and a success message must show

````
DELETE /api/v1/project/5/articles/20/categories HTTP/1.1
Host: blogs.k8s-dev.geeks.solutions
origin: https://blogmaiori.com
token: SFMyNTY.g2gDdAAAAARtAAAADGxvZ2luX2ZpZWxkc3QAAAABbQAAAAVlbWFpbG0AAAAfYS5zYXJraXMrdGVzdDVibG9nZGV2QGV3ZWV2LmNvbW0AAAARcHJvamVjdF9sb2dnZWRfaW5tAAAAGDY1YWUyYTg5MTM1MzE2MDAwNzlmNzI4Nm0AAAAKdG9rZW5fdHlwZW0AAAAGbm9ybWFsbQAAAAd1c2VyX2lkbQAAABg2NWIyMWY3ZjEzNTMxNjAwMDdiNmNjYzBuBgBHndbqjQFiAAFRgA.I1JQIZStkFfWC8O3Gu3ww4YsZeAuJOo2tm0wTrEDMDY
Content-Type: application/json
Content-Length: 19

{"categories": [2]}
`````

- [ ] To remove a suggested article for an article, the below endpoint must be  called and a success message must show

````
DELETE /api/v1/project/5/articles/6/suggested HTTP/1.1
Host: blogs.k8s-dev.geeks.solutions
origin: https://blogmaiori.com
token: SFMyNTY.g2gDdAAAAARtAAAADGxvZ2luX2ZpZWxkc3QAAAABbQAAAAVlbWFpbG0AAAAfYS5zYXJraXMrdGVzdDVibG9nZGV2QGV3ZWV2LmNvbW0AAAARcHJvamVjdF9sb2dnZWRfaW5tAAAAGDY1YWUyYTg5MTM1MzE2MDAwNzlmNzI4Nm0AAAAKdG9rZW5fdHlwZW0AAAAGbm9ybWFsbQAAAAd1c2VyX2lkbQAAABg2NWIyMWY3ZjEzNTMxNjAwMDdiNmNjYzBuBgBHndbqjQFiAAFRgA.I1JQIZStkFfWC8O3Gu3ww4YsZeAuJOo2tm0wTrEDMDY
Content-Type: application/json
Content-Length: 18

{"suggested": [2]}
````

**Delete article**

- [ ] There is a delete article option and when clicking on it there will be a warning asking if I am sure i want to delete it 
- If I cancel nothing happened
- If I confirm the article is deleted and you are redirected to the listing of articles with the article removed from the listing

````
DELETE /api/v1/project/5/articles/30 HTTP/1.1
Host: blogs.k8s-dev.geeks.solutions
token: SFMyNTY.g2gDdAAAAARtAAAADGxvZ2luX2ZpZWxkc3QAAAABbQAAAAVlbWFpbG0AAAAfYS5zYXJraXMrdGVzdDVibG9nZGV2QGV3ZWV2LmNvbW0AAAARcHJvamVjdF9sb2dnZWRfaW5tAAAAGDY1YWUyYTg5MTM1MzE2MDAwNzlmNzI4Nm0AAAAKdG9rZW5fdHlwZW0AAAAGbm9ybWFsbQAAAAd1c2VyX2lkbQAAABg2NWIyMWY3ZjEzNTMxNjAwMDdiNmNjYzBuBgBHndbqjQFiAAFRgA.I1JQIZStkFfWC8O3Gu3ww4YsZeAuJOo2tm0wTrEDMDY
origin: https://blogmaiori.com
````

**Acceptance testing**

- [ ] Edit an article not published is successfull
- [ ] Edit an article published will create a draft
- [ ] Publish the draft, the original article will be updated and the  the draft removed
- [ ] Publish an article successfull
- [ ] Unpublish an article successfull
- [ ] Try to publish/unpublish with a user not an admin or publisher
- [ ] Remove category from an article should be successful with a success message
- [ ] Remove a suggested article from an article, should be successful with a success message
- [ ] Delete an article should open a popup and regarding if you confirm or not, it should remove the  article or not

**Comment by mahfouzhseineweev** [comment]
@akramsarkis I did what I could do for the create and edit issues. 
For now you should skip the edit suggested, edit categories, medias.
For the edit suggested and categories, I am waiting answer of Julien to know how I can proceed with it.

To test both issues, you need to use the below props values:

```
serverUrl: 'https://blogs.k8s-dev.geeks.solutions/api/v1',
projectIdProp: '5',
authToken: 'SFMyNTY.g2gDdAAAAARtAAAADGxvZ2luX2ZpZWxkc3QAAAABbQAAAAVlbWFpbG0AAAAfYS5zYXJraXMrdGVzdDVibG9nZGV2QGV3ZWV2LmNvbW0AAAARcHJvamVjdF9sb2dnZWRfaW5tAAAAGDY1YWUyYTg5MTM1MzE2MDAwNzlmNzI4Nm0AAAAKdG9rZW5fdHlwZW0AAAAGbm9ybWFsbQAAAAd1c2VyX2lkbQAAABg2NWIyMWY3ZjEzNTMxNjAwMDdiNmNjYzBuBgAc51i2kQFiAAFRgA.jg17okb3Cs5sA64jHW5YuFdqypTwqb147LGG9mYNV3k',
blogByIdUriProp: "https://blogs.k8s-dev.geeks.solutions/api/v1/project/5/articles/",
createBlogUriProp: "https://blogs.k8s-dev.geeks.solutions/api/v1/project/5/articles",
blogsUriProp: "https://blogs.k8s-dev.geeks.solutions/api/v1/project/5/articles/",
authorsUriProp: 'https://blogs.k8s-dev.geeks.solutions/api/v1/project/5/users',
categoriesUriProp: 'https://blogs.k8s-dev.geeks.solutions/api/v1/project/5/categories',
```
